# Ansible Inventory for Employee Helpdesk System
# Student: Aditya Singh (Roll No: 23102B0010)

[target_nodes]
localhost ansible_connection=local

[web_servers]
localhost ansible_connection=local

[all:vars]
ansible_python_interpreter=/usr/bin/python3
app_port=8082
app_user=helpdesk
app_dir=/opt/helpdesk
